package test;

import main.config.CustomException;

public class test {
    public static void main(String[] args) throws CustomException {
        // testCode
//        UserDao userDao = new UserDao();
//        System.out.println(userDao.signUp(new User("username:l000126,password:dlgusdn!00,nickname:nickname1")));
//        System.out.println(userDao.login(new User("username:l000126,password:dlgusdn!00,nickname:nickname1")).getUserId());


//        RoomDao roomDao = new RoomDao();
//        roomDao.createRoom("이현우의채팅방", 3L);
//        UserController userController = UserController.getInstance();
//        userController.callService("POST",
//                // body
//                "username:testUsername," +
//                "password:testPassword," +
//                "nickname:testNickname");

//        new ProxyController().callService("GET /user", "username:l000127,password:dlgusdn!00");
    }
}
